name: is_search_page
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  http: ^1.2.1
  flutter_riverpod: ^2.5.1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png

  android_12:
    image: assets/logo.png
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
   - assets/logo.png