// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'internship.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Internship _$InternshipFromJson(Map<String, dynamic> json) => Internship(
      (json['id'] as num).toInt(),
      json['title'] as String,
      json['employment_type'] as String,
      ApplicationStatusMessage.fromJson(
          json['application_status_message'] as Map<String, dynamic>),
      json['job_title'] as String?,
      json['work_from_home'] as bool,
      json['segment'] as String,
      json['segment_label_value'] as String?,
      json['internship_type_label_value'] as String?,
      (json['job_segments'] as List<dynamic>).map((e) => e as String).toList(),
      json['company_name'] as String,
      json['company_url'] as String,
      json['is_premium'] as bool,
      json['is_premium_internship'] as bool,
      json['employer_name'] as String,
      json['company_logo'] as String,
      json['type'] as String,
      json['url'] as String,
      (json['is_internchallenge'] as num).toInt(),
      json['is_external'] as bool,
      json['is_active'] as bool,
      json['expires_at'] as String,
      json['closed_at'] as String,
      json['profile_name'] as String,
      json['part_time'] as bool,
      json['start_date'] as String,
      json['duration'] as String,
      Stipend.fromJson(json['stipend'] as Map<String, dynamic>),
      json['salary'] as String?,
      json['job_experience'] as String?,
      json['experience'] as String,
      json['posted_on'] as String,
      (json['posted_on_date_time'] as num?)?.toInt(),
      json['application_deadline'] as String,
      json['expiring_in'] as String,
      json['posted_by_label'] as String,
      json['posted_by_label_type'] as String,
      (json['location_names'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      (json['locations'] as List<dynamic>)
          .map((e) => Location.fromJson(e as Map<String, dynamic>))
          .toList(),
      json['start_date_comparison_format'] as String,
      json['start_date1'] as String,
      json['start_date2'] as String,
      json['is_ppo'] as bool,
      json['is_ppo_salary_disclosed'] as bool,
      json['ppo_salary'] as String?,
      json['ppo_salary2'] as String?,
      json['ppo_label_value'] as String,
      json['to_show_extra_label'] as bool,
      json['extra_label_value'] as String,
      json['is_extra_label_black'] as bool,
      (json['campaign_names'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      json['campaign_name'] as String,
      json['to_show_in_search'] as bool,
      json['campaign_url'] as String,
      json['campaign_start_date_time'] as String?,
      json['campaign_launch_date_time'] as String?,
      json['campaign_early_access_start_date_time'] as String?,
      json['campaign_end_date_time'] as String?,
      (json['labels'] as List<dynamic>)
          .map((e) => Label.fromJson(e as Map<String, dynamic>))
          .toList(),
      json['labels_app'] as String,
      (json['labels_app_in_card'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      json['is_covid_wfh_selected'] as bool,
      json['to_show_card_message'] as bool,
      json['message'] as String,
      json['is_application_capping_enabled'] as bool,
      json['application_capping_message'] as String,
      (json['override_meta_details'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      json['eligible_for_easy_apply'] as bool,
      json['eligible_for_b2b_apply_now'] as bool,
      json['to_show_b2b_label'] as bool,
      json['is_international_job'] as bool,
      json['to_show_cover_letter'] as bool,
      json['office_days'] as String?,
    );

Map<String, dynamic> _$InternshipToJson(Internship instance) =>
    <String, dynamic>{
      'id': instance.id,
      'title': instance.title,
      'employment_type': instance.employmentType,
      'application_status_message': instance.applicationStatusMessage,
      'job_title': instance.jobTitle,
      'work_from_home': instance.workFromHome,
      'segment': instance.segment,
      'segment_label_value': instance.segmentLabelValue,
      'internship_type_label_value': instance.internshipTypeLabelValue,
      'job_segments': instance.jobSegments,
      'company_name': instance.companyName,
      'company_url': instance.companyUrl,
      'is_premium': instance.isPremium,
      'is_premium_internship': instance.isPremiumInternship,
      'employer_name': instance.employerName,
      'company_logo': instance.companyLogo,
      'type': instance.type,
      'url': instance.url,
      'is_internchallenge': instance.isInternchallenge,
      'is_external': instance.isExternal,
      'is_active': instance.isActive,
      'expires_at': instance.expiresAt,
      'closed_at': instance.closedAt,
      'profile_name': instance.profileName,
      'part_time': instance.partTime,
      'start_date': instance.startDate,
      'duration': instance.duration,
      'stipend': instance.stipend,
      'salary': instance.salary,
      'job_experience': instance.jobExperience,
      'experience': instance.experience,
      'posted_on': instance.postedOn,
      'posted_on_date_time': instance.postedOnDateTime,
      'application_deadline': instance.applicationDeadline,
      'expiring_in': instance.expiringIn,
      'posted_by_label': instance.postedByLabel,
      'posted_by_label_type': instance.postedByLabelType,
      'location_names': instance.locationNames,
      'locations': instance.locations,
      'start_date_comparison_format': instance.startDateComparisonFormat,
      'start_date1': instance.startDate1,
      'start_date2': instance.startDate2,
      'is_ppo': instance.isPpo,
      'is_ppo_salary_disclosed': instance.isPpoSalaryDisclosed,
      'ppo_salary': instance.ppoSalary,
      'ppo_salary2': instance.ppoSalary2,
      'ppo_label_value': instance.ppoLabelValue,
      'to_show_extra_label': instance.toShowExtraLabel,
      'extra_label_value': instance.extraLabelValue,
      'is_extra_label_black': instance.isExtraLabelBlack,
      'campaign_names': instance.campaignNames,
      'campaign_name': instance.campaignName,
      'to_show_in_search': instance.toShowInSearch,
      'campaign_url': instance.campaignUrl,
      'campaign_start_date_time': instance.campaignStartDateTime,
      'campaign_launch_date_time': instance.campaignLaunchDateTime,
      'campaign_early_access_start_date_time':
          instance.campaignEarlyAccessStartDateTime,
      'campaign_end_date_time': instance.campaignEndDateTime,
      'labels': instance.labels,
      'labels_app': instance.labelsApp,
      'labels_app_in_card': instance.labelsAppInCard,
      'is_covid_wfh_selected': instance.isCovidWfhSelected,
      'to_show_card_message': instance.toShowCardMessage,
      'message': instance.message,
      'is_application_capping_enabled': instance.isApplicationCappingEnabled,
      'application_capping_message': instance.applicationCappingMessage,
      'override_meta_details': instance.overrideMetaDetails,
      'eligible_for_easy_apply': instance.eligibleForEasyApply,
      'eligible_for_b2b_apply_now': instance.eligibleForB2bApplyNow,
      'to_show_b2b_label': instance.toShowB2bLabel,
      'is_international_job': instance.isInternationalJob,
      'to_show_cover_letter': instance.toShowCoverLetter,
      'office_days': instance.officeDays,
    };
